### ISSUE TITLE
GD Library bug

### ISSUE THREAD

**Issue by jopbouckaert** [vives-projectwerk2-2019/bug-kiosk#4]
GD Library extension not available on server.

**Comment by JensVercruysse** [comment]
![image](https://user-images.githubusercontent.com/36663522/56961668-969ff100-6b54-11e9-81db-9657db78a5e7.png)

**Comment by JensVercruysse** [comment]
fixed by @sillevl :)

**Comment by sillevl** [comment]
I did not yet test if the problem is solved....

**Comment by sillevl** [comment]
2f7a4b2e22e6da2255372b28285af51d9f0e9190 did not solve it yet, reopening the issue.

**Comment by JensVercruysse** [comment]
ah wat, ik had het getest en het werkte

**Comment by JensVercruysse** [comment]
ik kan nu foto's uploaden op server

**Comment by sillevl** [comment]
`png` seems to work, but `jpg` not

**Comment by sillevl** [comment]
https://php.net/manual/en/function.imagecreatefromjpeg.php#70832

**Comment by sillevl** [comment]
solved in bc20bc98977d0b9f034d8243f0432490e6cf5ca5
